@startuml
header reto_serverless
footer Página %page% of %lastpage%\nmade with ♥ by Nequi
title Diagrama de Secuencia
autonumber
actor Lambda_Invoke
boundary reto_serverless
entity nequi_aws_dynamodb
Lambda_Invoke -> reto_serverless: Llamado de la lambda (key, region)
activate reto_serverless
reto_serverless -> nequi_aws_dynamodb: getItem(nequi-parameters-qa)
activate nequi_aws_dynamodb
note right
  Se obtiene el item con el
  parámetro de busqueda
end note
return item encontrado
return item consultado

@enduml